### ISSUE TITLE
Note on fusion360

### ISSUE THREAD

**Issue by Sesam31** [Kndndrj/wiener#1]
Hi, I just installed fusion360 using wiener, everything works fine but I just wanted to point out that if the program doesn't start right after installing it you just have to reboot your system and everything will start working!!!
Keep up the good work!!! :)

**Comment by Sesam31** [comment]
I have used the program to design and export a 3d model and everything worked fine.
As a sidenote I just wanted to point out that the .desktop file doesn't launch the program.
To run fusion I open the directory where the .lnk file is stored (~/.local/share/wiener/fusion360/drive_c/users/Public/Desktop) and I had to execute the following command:
`env WINEPREFIX="/home/daniele/.local/share/wiener/fusion360" wine ./Autodesk\ Fusion\ 360.lnk 
`
Then the program started properly.
Is there a way to fix this problem?

P.S.
I'm running gnome-shell as a de (don't know if that makes a difference).

**Comment by Sesam31** [comment]
I figured it out, in gnome shell the .desktop file can be launched from the menu if it's in the folder `~/.local/share/applications`, after adding it here it launches like a charm.

**Comment by kndndrj** [comment]
Hey, sorry for the late reply. Thanks for taking interest in wiener. I see that you have figured out the solutions by yourself by now.
I'd have to take a look at the problems again to be sure, but as far as i know, wine should automatically create a `.desktop` file in `~/.local/share/applications/wine` (or something along these lines). I'll check if I have some time and will let you know if i find anything interesting.

**Comment by Sesam31** [comment]
Yes it did, but for some reason it appeared in the menu only after I rebooted the system.
